### ISSUE TITLE
maintainer not working on this anymore?

### ISSUE THREAD

**Issue by SamuelBrucksch** [openhab/openhab-alexa#107]
Hi,

to me it looks like noone works here actively anymore on answering issues or merging PRs. There are a lot of open PRs related to v3 and the last change on the v3 branch was 7 months ago. 

I saw that multiple people did changes and worked on the v3 branch, and as this seems to be the central point where it all comes together, it would be nice, if other people could take over or at least are allowed to merge PRs in here so we can get all the latest changes and do not have to collect them from multiple  git repos.

The earliest PR for example is from may 2018, there were some replies back in october but after that its still dead.

If this is not maintained anymore i would propose to open a new repository where all people that were active here could work on the code so we at least have a base code where we can work on to push the v3 implementation of this skill.

**Comment by lpghartz** [comment]
I agree, it seems completely abandoned. There's a lot of people doing DIY deployments of it to work around the fact that it hasn't been updated in ages. 

I suspect most people who are dinking around with it have just forked it themselves. Given that this is in a project within the openhab repo, there shouldn't need to be any need to create a new repository -- the abandonment of it, in theory, should just need to be brought to the attention of the rest of the OpenHAB team, who can give someone else admin access to this repo -- its possible they're not even aware of it. Its not clear how to contact them, though, from the website. 

IMO, doing a new repo will just end up fragmenting things, particularly given you ideally want whoever currently has the publishing rights to Amazon involved (which would be another issue if the current owner of this repo is also that person). Otherwise you'll end up with a confusing situation with an "official" (old) skill, and an "unofficial" new skill.

**Comment by digitaldan** [comment]
Hi guys, it's not abandoned, I just have been pulled off supporting myopenhab work and trying to get our v2 version of this app in all countries.  This skill is next on my list of things to tackle after I do a hardware upgrade to our cloud service (maybe next week).  The v3 branch is the right place for development, we kinda got stuck on async notifications, but for the most part its nearly ready as a v2 replacement.  

As soon as we can be accepted into the remaining countries (the app in is review right now).  I would like to use the beta channel feature and be able to push v3 out to early adopters.

If you have additional features or changes you would like to add, please submit them as PR's here.

Thanks.

**Comment by digitaldan** [comment]
>Is there something like a TODO list or so whats still missing on v3?

There is not yet, but that would be helpful for sure.

**Comment by SamuelBrucksch** [comment]
Ok if you find anything i could help with just tell me, in the meantime i will test with my self deployed v3 skill.

**Comment by digitaldan** [comment]
So now that we are in all countries with v2 I am ramping up v3 development, I plan to move the v3 branch to master after a few tweaks.
