### ISSUE TITLE
[V3] Add security panel controller support

### ISSUE THREAD

**Issue by smhgit** [openhab/openhab-alexa#111]
[SecurityPanelController](https://developer.amazon.com/docs/device-apis/alexa-securitypanelcontroller.html)

**Comment by digitaldan** [comment]
Agreed, that would be cool

**Comment by digitaldan** [comment]
So i have started thinking about this one, my thoughts so far as sample items would be:

```
Group  TestAlarm "Alarm" {alexa="SecurityPanelController"}
String TestAlarmModeCommand "Alarm"  (TestAlarm) { alexa="SecurityPanelController.command" [ARMED_AWAY="away",ARMED_STAY="stay",ARMED_NIGHT="night",DISARMED="disarm",pinSupport=true,supportsArmInstant=true] }
String TestAlarmModeState "Alarm"  (TestAlarm) { alexa="SecurityPanelController.armState" [ARMED_AWAY="away",ARMED_STAY="stay",ARMED_NIGHT="night",DISARMED="disarm"] }
Switch TestAlarmBurglaryAlarm "Burglary in Alarm" (TestAlarm) {alexa="SecurityPanelController.burglaryAlarm"}
Switch TestAlarmFireAlarm "FIre in Alarm" (TestAlarm) {alexa="SecurityPanelController.fireyAlarm"}
Switch TestAlarmCarbonMonoxideAlarm "Carbon Monoxide in Alarm" (TestAlarm) {alexa="SecurityPanelController.carbonMonoxideAlarm"}
Switch TestAlarmWwaterAlarm "Water in Alarm" (TestAlarm) {alexa="SecurityPanelController.waterAlarm"}
Number TestAlarmExitDelayInSeconds "Exit Delay In Seconds" (TestAlarm) {alexa="SecurityPanelController.exitDelayInSeconds"}
```

@jsetton didn't know if you had started working on this, I have a rough sketch out of the capabilities and properties, but not much more at this point. 

 For pin support when sending a command, I was thinking we could append the pin to the command if enabled,  so when arming we would send "away:1234" as a string.  If there is a better idea, i'm all ears :-)

**Comment by jsetton** [comment]
Since you add this one assigned to yourself, I left that one last 😄 I was going to aim to range, toggle and time hold capabilities next.

Your sketch looks good. A couple things to note:

- The group endpoint needs to match the display category. Strange enough, the [main documentation](https://developer.amazon.com/docs/device-apis/alexa-discovery.html#display-categories) that lists all their existing categories isn't up to date. Anyway, the category for this one is `SECURITY_PANEL`.  So, the endpoint group should be `Endpoint.SecurityPanel` and we will need to add camel case reformatting when [handling a group category](https://github.com/openhab/openhab-alexa/blob/v3/ohConnectorV3.js#L775).

- To handle the difference between alarm mode command and state, we should use the [item sensor concept](https://github.com/openhab/openhab-alexa/blob/v3/USAGE.md#supported-item-mapping-metadata) (end of section) I added to accomplish that type of scenario instead of creating an extra non-documented property. This is similar to lock control. Not everyone may have two different channels to get current state. So using that concept gives that flexibility.

- For the arm mode, we should probably allow `Number` item type as well similar to thermostat mode support (e.g. `[DISARMED=0, ARMED_STAY=1, ARMED_AWAY=2, ARMED_NIGHT=3]`).

- In regards to the pin code support, I am fine with the format but we would only allow it for `String` item type.

- For the `supportsArmInstant=false` flow, having two separate items will be a pain in the current workflow and also cost an extra rest call. I think we should have a parameter with the delay amount such as `exitDelay=<delay>`, to replace `supportsArmInstant`. 

Here is my revise sketch:
```
Group  TestAlarm "Alarm" {alexa="SecurityPanel"}
String TestAlarmMode "Alarm"  (TestAlarm) {alexa="SecurityPanelController.armState" [ARMED_AWAY="away",ARMED_STAY="stay",ARMED_NIGHT="night",DISARMED="disarm",exitDelay=300,supportsPinCodes=true,itemSensor="TestAlarmModeStatus"]}
String TestAlarmModeStatus "Alarm Status"  (TestAlarm)
Switch TestAlarmBurglaryAlarm "Burglary in Alarm" (TestAlarm) {alexa="SecurityPanelController.burglaryAlarm"}
Switch TestAlarmFireAlarm "Fire in Alarm" (TestAlarm) {alexa="SecurityPanelController.fireAlarm"}
Switch TestAlarmCarbonMonoxideAlarm "Carbon Monoxide in Alarm" (TestAlarm) {alexa="SecurityPanelController.carbonMonoxideAlarm"}
Switch TestAlarmWaterAlarm "Water in Alarm" (TestAlarm) {alexa="SecurityPanelController.waterAlarm"}
```

**Comment by digitaldan** [comment]
Thank @jsetton  for the feedback, going to work on this today.

**Comment by jsetton** [comment]
At this point, I would say you should wait for my refactoring PR. Although you can start thinking about the logic 😄 but a lot of the enhancement I added will make this very easy to implement. I am aiming to get the PR out by the end of the day.

**Comment by digitaldan** [comment]
Sounds good, I definitely have other things to work on.  If you already have this thought through or think it would be easier for you to incorporate , feel free to take it.
