### ISSUE TITLE
[v3] Attaching Door/Lock to Rollershutter responds with not supported

### ISSUE THREAD

**Issue by Flole998** [openhab/openhab-alexa#125]
I was trying to make Alexa capable of controlling my Garage door by adding the Lockcontroller.lockstate interface to my Rollershutter item, without setting a category it just shows up in jammed state and when I try to send commands it tells me that it's not supported. When i set category="DOOR" I am unable to control it or see a status at all (probably it's not supported, at least not in my language)

This was tested using German Alexa.

**Comment by jsetton** [comment]
`LockController.lockState` can only be mapped to a switch item. It is expecting either ON or OFF state and will default to jammed state if neither are found.

You can refer to the [documentation](https://github.com/openhab/openhab-alexa/tree/v3#supported-item-mapping-metadata).

**Comment by Flole998** [comment]
Can this be changed in order to support Garagedoors that report a percentage? Or maybe someone wants to Pin protect rollershutters, thats where this could be useful aswell.

**Comment by jsetton** [comment]
You can always handle this on the OH side by using a virtual switch to interact with your rollershutter item.

**Comment by Flole998** [comment]
Yes of course that would be possible, it would be easier though to allow directly connecting a lock to a rollershutter (or is there anything preventing that). Especially when talking about lot's of items adding virtual switches makes it all more complicated than it has to be. If there's no way to allow this in the skill it's of course different, but if it's just not implemented yet we should keep this open as a feature request. I can't think of a negative consequence that might be caused by adding it either, did I miss something there and didn't think it through completely?

**Comment by digitaldan** [comment]
I'm ok to keep this open, but i do want to stress that our beta testing should be focused on making sure the basic API set is working correctly.  Locks are a ON or OFF state, roller shutters do not support such a state (unlike say a dimmer) , so for the time being I would put off corner cases like this until we have a stable release out.

**Comment by jsetton** [comment]
@Flole998 as I mentioned in #198,  there are no Alexa-specific controllers for roller shutters as of yet. I believe that adding support for these edge cases to accommodate the lack of support on the Alexa side is not the way to go.

For your example, you can set your garage door device to use the "Switchable" metadata label and set Alexa routines to use open/close utterances to control that device.

* _Alexa, open garage door_ => Set Garage Door to 0%
* _Alexa, close garage door_ => Set Garage Door to 100%

Also, since Alexa routines utterances takes precedence over skill supported ones, you can set other permutations such as lock/unlock or raise/lower as well.
