### ISSUE TITLE
What route is the skill using from start to end?

### ISSUE THREAD

**Issue by Chrunchy** [openhab/openhab-alexa#15]
Is it possible to have explained how the communcation goes after the command is initiated by voice to Alexa?

How i see it, it's from Alexa device -> Skill -> AWS Lambda -> OpenHab2.
How does the Lambda service communicate with OpenHab2 in this way, if port 443 is not forwarded to the server hosting OpenHab2?

The only way i see that possible would be by Alexa Device -> Skill -> AWS Lambda -> Alexa device -> OpenHab2, since this wouldn't require any portforwarding if the alexa could send the instructions to OpenHAB, since it's on the same network.

**Comment by cole701** [comment]
If I am following this topic correctly, then myopenHAB is in there and the interface into openHAB...Sent from Xfinity Connect Mobile App------ Original Message ------From: ChrunchyTo: openhab/openhab-alexaCc: SubscribedSent: February 24, 2017 at 6:02 PMSubject: [openhab/openhab-alexa] What route is the skill using from start to end? (#15)Is it possible to have explained how the communcation goes after the command is initiated by voice to Alexa?
How i see it, it's from Alexa device -> Skill -> AWS Lambda -> OpenHab2.
How does the Lambda service communicate with OpenHab2 in this way, if port 443 is not forwarded to the server hosting OpenHab2?
The only way i see that possible would be by Alexa Device -> Skill -> AWS Lambda -> Alexa device -> OpenHab2, since this wouldn't require any portforwarding if the alexa could send the instructions to OpenHAB, since it's on the same network.

**Comment by Chrunchy** [comment]
That makes sense. So My.openhab has a pipe in to the hosted openhab service running on a raspberry or similar.

So the traffic would somehow go: Alexa -> Skill -> AWS -> My.openhab (using OAuth) -> local OpenHab?

**Comment by cole701** [comment]
I'm no expert yet but yes, the way I read it that is the expected communication flow...Sent from Xfinity Connect Mobile App------ Original Message ------From: ChrunchyTo: openhab/openhab-alexaCc: Rich Cole, CommentSent: February 24, 2017 at 6:15 PMSubject: Re: [openhab/openhab-alexa] What route is the skill using from start to end? (#15)That makes sense. So My.openhab has a pipe in to the hosted openhab service running on a raspberry or similar.
So the traffic would somehow go: Alexa -> Skill -> AWS -> My.openhab (using OAuth) -> local OpenHab?

**Comment by digitaldan** [comment]
If you are using our published version of this then the flow is Echo/Dot -> Alexa API -> This Skill (Lambda) -> myopenhab.org -> OH.   If you are so inclined the skill may also be deployed on your own and pointed directly to your OH instance, but this is not a trivial setup.
