### ISSUE TITLE
[v3] Globals State Issue

### ISSUE THREAD

**Issue by digitaldan** [openhab/openhab-alexa#157]
So i was looking at this:
https://github.com/openhab/openhab-alexa/blob/71e08eba4033226c8068e1ac85708ef8eae97282/ohConnectorV3.js#L25

I'm not sure how isolated lambda requests are, but if this was a regular node app, this would lead to requests overwriting other requests state during concurrent requests.  @jsetton WDYT?

**Comment by jsetton** [comment]
Based on my understanding, lambda requests are bounded by an execution context and run synchronously in that context. Once a request is completed, that context can be reuse.

I think we would run into an issue if we were relying on that variable to make subsequent updates. But, we are overwriting it on every execution. And if you concern about `directive`, why not `properMap` global variable as well?

Maybe I am missing something. Have you noticed otherwise looking at the function logs?

On a side note, do you have preliminary lambda runtime stats from the beta skill? I am curious to see how much the average execution time increased compared to v2.

**Comment by jsetton** [comment]
Interesting article about lambda caching with global variables.

https://medium.com/tensult/aws-lambda-function-issues-with-global-variables-eb5785d4b876

**Comment by digitaldan** [comment]
>And if you are concerned about `directive`, why not `properMap` global variable as well?

I am, i just reference the first global there, but i was referring to all of them

>https://medium.com/tensult/aws-lambda-function-issues-with-global-variables-eb5785d4b876

Good find, yep, this is what i am afraid of, i think we should remove to be safe, wdyt?

**Comment by jsetton** [comment]
What are you afraid of? There should not be any concurrency issue here. The only issue is that the previous global variables content will be available when a new request is processed by the same execution context, but will be overwritten right away by the only exported function `handleRequest` from the `ohConnectorV3` module.

https://github.com/openhab/openhab-alexa/blob/71e08eba4033226c8068e1ac85708ef8eae97282/ohConnectorV3.js#L34-L37

**Comment by digitaldan** [comment]
I get its not a problem now, but I worry in the future that it could bite us with other developers contributing, or even me forgetting these are global.  During some refactor the logic changes and when a dev expect it to be null, its actually populated with the last request.

**Comment by jsetton** [comment]
I am adding the changes for this one in my refactoring PR.
