### ISSUE TITLE
[v3] Allow usage without cloud

### ISSUE THREAD

**Issue by Flole998** [openhab/openhab-alexa#163]
I just had some thoughts about not requiring myOpenHAB anymore for the Alexa Skill if someone prefers that, but without self-hosting the skill: What about adding a database that contains a User-URL Mapping and if it's defined use that? Has someone else already thought about that? I think it would be great to allow usage of the skill without using any kind of cloud, especially if it's really as simple as having a database.

**Comment by jsetton** [comment]
Based on my understanding, the linking process part of enabling the official Alexa skill requires to be pointing to the myopenHAB OAuth2 endpoint. This is what allows the skill to access your openHAB server, without actually storing your username and password, opposed to how it is done when self-hosting the skill where the authenticating is done at the Lambda function level.

Although, you could also setup your own cloud connector instance and setup the same OAuth2 integration with your self-hosted skill if you are trying to remove the myopenHAB cloud dependency but since we are talking about Alexa, I can't see how you can remove any kind of cloud dependencies.

**Comment by Flole998** [comment]
Yes exactly that's also how I understand it. But if we store a User-URL-Username-Password combination in a database it could work (although plaintext passwords shouldn't be stored).

Of course you will always have the alexa cloud dependency, but if we can make the myOpenHAB dependency optional it would be great in my opinion.

**Comment by jsetton** [comment]
So this is technically not possible, a skill can only point to a pre-configured OAuth2 endpoint. There is no options for users to change this configuration during the skill account linking process.

The only recommended solution here would be use your private stack including setting up your own cloud connector instance and your own Alexa skill.

**Comment by Flole998** [comment]
This would be possible, I have described a way to do it above. While this would still require the cloud to be there, it doesn't need to be used anymore.
