### ISSUE TITLE
[V3] Rollershutter ON/OFF not converted to 100/0

### ISSUE THREAD

**Issue by RobertHerter** [openhab/openhab-alexa#198]
Alexa send ON OFF to rollershutter Items wich is not working. Should be converted to 100/0 %

**Comment by fmeies** [comment]
I can confirm this. Unfortunately, the OH rollershutter item only supports UpDown, StopMove, Percent but not OnOff. A conversion from OnOff in the alexa skill seems to be the wrong place for fixing this although I have to admid that I did exactly this in my running skill instance as a workaround.

**Comment by jsetton** [comment]
The problem here is that there are no Alexa-specific controllers for shades/binds as of yet. Comparing to the [v2 skill](https://github.com/openhab/openhab-alexa/blob/809cc3086511d1e580d55bdd8716f3d422968026/oh2.js#L685), the PowerController interface shouldn't have been associated to rollershutter items when using the `Switchable` metadata label.

Updating the PowerController interface to send something else than ON/OFF seems more a hack from the skill perspective and as @fmeis mentioned what command should be sent Up/Down, Stop/Move or 0/100% for rollershutters?

This is why I would recommend handling this with Alexa routines that open/close blinds by setting the percent level, until Amazon provides a new interface to control these devices. You can set these via the mobile app.

* _Alexa, open bedroom blinds_ => Set Bedroom Blinds to 0%
* _Alexa, close bedroom blinds_ => Set Bedroom Blinds to 100%

On a side note, make sure to vote for the blinds integration feature request on the [Alexa user voice](https://alexa.uservoice.com/forums/913024-alexa-smart-home/suggestions/34277038-support-for-blinds-or-shades-in-smart-home-with) website.
