### ISSUE TITLE
Ask doco incomplete?

### ISSUE THREAD

**Issue by dastrix80** [openhab/openhab-alexa#229]
Hi All

Seems the deployment of the lambda has changed to use ask. The documentation on the main page appears incomplete or at least missing detail

I installed ask and run it as per the instructions and I get this:

ubuntu@ip-172-31-2-182:~$  ask init
Could not open configuration file init

Can someone please assist? Thanks

**Comment by jsetton** [comment]
You need to run the ask-cli commands inside the project folder.

**Comment by dastrix80** [comment]
thanks jsetton!

now I receive this :(


ubuntu@ip-172-31-2-182:~/IHP-Alexa$ ask init
/home/ubuntu/.nvm/versions/node/v7.10.1/lib/node_modules/ask-cli/node_modules/open/index.js:29
                ...options
                ^^^
SyntaxError: Unexpected token ...
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/ubuntu/.nvm/versions/node/v7.10.1/lib/node_modules/ask-cli/lib/utils/lwa.js:1:76)

**Comment by jsetton** [comment]
You should probably upgrade your nodejs install to a [current release](https://github.com/nodejs/Release#release-schedule).

**Comment by dastrix80** [comment]
its on v7.10.1 because thats what openhab cloud needs

**Comment by jsetton** [comment]
You will need to update to at least version 8+. The Alexa skill requires that version as well.

https://github.com/openhab/openhab-alexa/blob/f364bd20f11252e4bae073eaf516307f020f61e4/lambda/smarthome/package.json#L38-L40

**Comment by jsetton** [comment]
Coming back on this one. My last explanation related to the Alexa skill version requirement is actually not the reason for your issue but the fact that ask-cli is using the [spread operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax#Browser_compatibility) which is only supported in object literals from nodejs version 8.3.0.

I am going to close this one since this is not an issue with the skill. It looks like the [official ask-cli prerequisites](https://developer.amazon.com/docs/smapi/quick-start-alexa-skills-kit-command-line-interface.html#prerequisites) should be updated as it is still showing a minimum of version 6 requirement.
