### ISSUE TITLE
Discovery quietly fails

### ISSUE THREAD

**Issue by digitaldan** [openhab/openhab-alexa#252]
@jsetton  A few days back i mentioned i had an issue with my environment and was having trouble testing.  Turns out it was not my dev environment or skill setup, but something else.  Right now Alexa is not discovering any of my items, either in production or on my dev skill. Logging shows the discovery request and response back to Alexa, and it seems ok, but the Alexa app never finds anything.  as an experiment, i linked to a demo openHAB account and that did work, so it must be something with my own items. Very strange.  I'm going to look at it today as i can find some time, removing items until it starts to work.  Not sure if you had any guesses what it might be.  FYI you can see the request in cloudwatch , the event time (UTC) from the line  is 

13:39:04 2019-08-19T13:39:04.623Z	cbf7e8e2-d805-4a3e-8d73-75db78450f97	

https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#logEventViewer:group=/aws/lambda/openhab-alexa-v3;stream=2019/08/19/[$LATEST]49bf07c8e2134b969fca370b40d090f0;start=2019-08-18T13:35:42Z

(not sure how to link to a single line in cloudwatch)

**Comment by jsetton** [comment]
Interesting. I think I saw a [similar situation](https://community.openhab.org/t/alexa-smart-home-skill-v3-is-now-live/79848/115?u=jeshab) where I would see the v3 discovery response being sent out but for some unknown reason it wasn't processed on the Alexa side as the device remained as v2. That user eventually mentioned that he got it working. Not sure exactly what he did but I recommended him to unlink and link the skill again.

Looking at your discovery response is hard to tell what could be the issue. I ran the response data output through the schema validation and there were no errors. So it may be a problem on the Alexa side. When did it work the last time and what items you added/updated since that time? 

This is strange because usually if a device part of the discovery had an issue, it would just be ignored but the other valid devices would still be processed.

If you are interested in running the validation on your end, you can use this quick script:

```js
const { assert } = require('./lambda/smarthome/test/common.js');
const data = require('./data.json');

assert.validSchema(data);
```

**Comment by digitaldan** [comment]
well, mystery solved.  Sort of.

So i  was messing around with the Range Controller feature a while back, just curious what alexa would do with certain values.  I wrote the following item line, got distracted, and never bothered to finish it or event test it ( i completely forgot about it).  I did not notice anything until i deleted all my Alexa devices when moving between dev and prod skills.

```js
Group:Rollershutter:MAX MovieRoom_Shades "Shades [%s]" {alexa="RangeController.rangeValue [supportedRange="0:100:0",presets="0=Open:Up,100=Down,Close",friendlyNames="Blinds,Shades"]}
```

With this line in, Alexa will silently ignore the discovery response.

**Comment by jsetton** [comment]
> With this line in, Alexa will silently ignore the discovery response.

You probably trigger a bug on the Alexa side with range controller since it is fairly new implementation 😄 Anyway, we can add a protection against precision of `0`. Also, I think there is a typo in your `100` preset using a common instead column sign.
