### ISSUE TITLE
Reduce Cloudwatch logging

### ISSUE THREAD

**Issue by digitaldan** [openhab/openhab-alexa#275]
@jsetton I received a free tier usage limit message from Amazon about our cloudwatch logging.

```
AWS Free Tier Usage as of 09/11/2019 | AWS Free Tier Usage Limit
-- | --
4.3367 GB | 5 GB of Log Data Ingestion for Amazon Cloudwatch
```

We should probably lower the logging now if possible.

**Comment by jsetton** [comment]
I initially thought of just decreasing the log retention from 30 days to 14 days or even 7 days if necessary but I realized this is incoming logs.

So this is a tricky one, if we decrease the log level to warn, we would lose any kind of troubleshooting information.

I just added a Cloudwatch dashboard to monitor the incoming logs in the 3 regions. Looking at the historical data, we were well over the 5GB for the [last two weeks of August](https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#dashboards:name=openhab-alexa-v3;start=2019-08-15T00:00:00Z;end=2019-08-31T23:59:59Z) at around 13GB (probably due to debug level enabled at times) and we are already over the limit for this month after the [first two weeks of September](https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#dashboards:name=openhab-alexa-v3;start=2019-09-01T00:00:00Z;end=2019-09-15T23:59:59Z), close to 7GB.

Based on these values, I have decreased the log level to warn in the 3 regions for the time being. I will have to take a closer look to see what we can do but I feel we are going to have to limit most of it. I guess that's probably the reason why the v2 skill didn't logging much although looking at the data from earlier this year, it was logging about 500MB per month.

**Comment by jsetton** [comment]
@digitaldan I just submitted a PR to reduce the default logging size. Currently, the logs generated in the error channels are still quite big as they include the whole error object. The change also add an essential directive properties object to the log error for troubleshooting purpose. We should probably get this one out as soon as possible.

One point I am still on the fence is if we should exclude any status code errors from the error channel as well since these are the ones, especially code >= 500, that are generated the most currently. Maybe we should move the 500s into info channel instead.

What do you think?

**Comment by jsetton** [comment]
I went ahead and merged/pushed #277 to live skill.

We ended the [last two weeks of September](https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#dashboards:name=openhab-alexa-v3;start=2019-09-16T22:00:00Z;end=2019-09-30T00:00:00Z), after I decreased the log level, at around 1.2GB. The change should reduce the log size further.

**Comment by digitaldan** [comment]
Thanks !!! FYI i have been on the road non stop for the last couple weeks.  In October alone i will be on 20 flights, so i will definitely be MIA until first week in November 😢   After that i am planning not to Travel for the rest of year and get back to openHAB development.  Thanks for being on top of everything, the skill has turned out to be pretty awesome indeed.

**Comment by jsetton** [comment]
> Thanks for being on top of everything, the skill has turned out to be pretty awesome indeed.

👍 

I made an additional change #286 to move request error to warn log channel. We should be fine now in term of log size. I am going to close this one for now.
