### ISSUE TITLE
ModeController.mode and OFF command

### ISSUE THREAD

**Issue by oeiber** [openhab/openhab-alexa#345]
Hi,
I'm using ModeController.mode for choosing the lights in my garage. Switching between 1 and 2 works perfectly. But sending an OFF command seems not to be working. Alexa says "...does not support the command".

My item definition looks as follows:
`Number SWI10_Scene "Licht Garage"  <light_bulb>  {alexa="ModeController.mode" [supportedModes="0=Aus,1=Stufe 1,2=Stufe 2", actionMappings="Aus=0,Stufe 1=1,Stufe 2=2"]}`

Some sample phrases in german:
"Alexa, stell das Licht in der Garage auf Stufe 1" --> state switches to 1
"Alexa, stell das Licht in der Garage auf Stufe 2" --> state switches to 2
"Alexa, stell das Licht in der Garage auf Aus" --> alexa says, "Licht Garage unterstützt das nicht"

**Comment by jsetton** [comment]
I just ran a test using your item definition and it seems that you have to use the device name as it is defined to switch to "off" mode. This is probably a limitation on the Alexa side due to the overlapping with the PowerController interface.

"Alexa, stell das Licht Garage auf Aus"

As a side note, the `actionMappings` parameter in your item definition is incorrectly used . It should define supported [semantic extensions](https://www.openhab.org/docs/ecosystem/alexa/#semantic-extensions) if you intended to use some of them.

Also, for these kind of issues, I think it would be more appropriate to post on the [community forum](https://community.openhab.org/) so others that may have the same question can found a solution.
