### ISSUE TITLE
Alexa discovery fails using gpio and alexa version 3 tags

### ISSUE THREAD

**Issue by hardwi-s** [openhab/openhab-alexa#362]
I have a Raspberry Pi with a single gpio item. If I define it as
Switch LightSwitch "Light Switch" <switch> {alexa="Switchable" gpio="pin:17"}
then Alexa discovery fails to find it. I have to use the older style tagging to get it to work:
Switch LightSwitch "Light Switch" <switch> ["Switchable"] {gpio="pin:17"}

I couldn't find anything in the documentation which said I couldn't use multiple tags. Apologies if this is how it's supposed to work, I was expecting the binding to just ignore any tags it didn't understand.

**Comment by jsetton** [comment]
For usage questions, you should post on the [community forum](https://community.openhab.org/). Also, make sure to provide, in that post, as much details as possible including your item definitions, the exact utterances you requested, the voice response you got back and the change you were expecting. Thanks.

Also, make sure to go over the [troubleshooting guide](https://www.openhab.org/docs/ecosystem/alexa/#troubleshooting) so that you can exclude any common errors.

In terms of the item definitions you provided, both are valid and discoverable. So it's a matter of troubleshooting your environment at this point using the guide above.
