### ISSUE TITLE
Temperature with decimal

### ISSUE THREAD

**Issue by nighti** [openhab/openhab-alexa#37]
Alexa says in german in temp request only the value without decimal places.
Could the issue be the parseint function, instead of using parsefloat?
var value = parseInt(items.targetTemperature.state);

**Comment by Dom1n1c** [comment]
I can confirm that this issue is existing in German. 
Furthermore, the unit is not told and the location is not correct. 
For instance: OpenHAB offers an item with the value 20.9 (degree Celsius, since not tagged with 'Fahrenheit') 
Alexa says: Drinnen ist es 20

Translation: Inside it is 20 
(this makes no sense, if I request an outside temperature)

**Comment by digitaldan** [comment]
Thanks @nighti ! That's probably the issue, I will take a look tonight and try and get it fixed

**Comment by Dom1n1c** [comment]
Decimals were now announced.
But there is an issue with the spelling (in German)
Die Temperatur von Küche ist 22. 6 Grad (its spelled zweiundzwanzigster sechs Grad, in english this would be "22nd/twentysecond")

**Comment by nighti** [comment]
Alexa spells it like US date format. But that seems for me not an skill issue. 
More an alexa issue.
