### ISSUE TITLE
missing several display categories

### ISSUE THREAD

**Issue by ccutrer** [openhab/openhab-alexa#418]
the skill documentation references https://developer.amazon.com/en-US/docs/alexa/device-apis/alexa-discovery.html#display-categories, but there are lots of categories references on the latter that aren't actually supported by the skill. if you try to use them the device just comes through as a SWITCH (at least when I tried to use CHRISTMAS_TREE). additional missing example is WATER_HEATER.

**Comment by jsetton** [comment]
All the latest display categories are supported as [device types](https://next.openhab.org/docs/ecosystem/alexa/#device-types), in the upcoming major changes to the skill currently in [beta testing](https://community.openhab.org/t/openhab-skill-for-amazon-alexa-new-metadata-syntax-beta-test/125732) and soon to be released to the live skill.

As far as your observation, the current skill will fallback to the default category for a given capability. So since the ones you listed aren't supported, it is expected behavior.

**Comment by ccutrer** [comment]
Oh nice, thanks for pointing me in the right direction!
