### ISSUE TITLE
Support remote video player interface

### ISSUE THREAD

**Issue by GiviMAD** [openhab/openhab-alexa#467]
Support for the [remote video player](https://developer.amazon.com/en-US/docs/alexa/device-apis/alexa-remotevideoplayer.html) interface will be awesome.
I think it could very useful if we can get this value into a text item.
I don't know if I asking for something that could not be done, I have not experience developing skills, let me know.
Thanks in advance.

**Comment by jsetton** [comment]
We actually looked into this and possibility add other [Video Skill API](https://developer.amazon.com/en-US/docs/alexa/video/understand-the-video-skill-api.html) interfaces. However, Amazon decided to completely separate smart home from video skills requiring separate skills to handle each type. 

So due to the complexity, this is not something that we are looking to implement at the moment. Ideally, Amazon should make video capability part of [multi-capability skills](https://developer.amazon.com/en-US/docs/alexa/smarthome/about-mcs.html) ability.

**Comment by GiviMAD** [comment]
What a pity, I hope this changes in the future. 
But thanks for the explanation. 
Regards!
