### ISSUE TITLE
Support connection to self-hosted openhab-cloud solution

### ISSUE THREAD

**Issue by terler188** [openhab/openhab-alexa#58]
Currently the skill only points to the "myopenhab.org" solution (afaik). But the openhab-cloud solution also offers the oppertunity to host it yourself. Therefore the skill should provide the possibility to enter the URL of a self hosted openhab-cloud solution. "myopenhab.org" could be the default value for this field.

**Comment by jsetton** [comment]
As far as I know, you wouldn't be able to do this using the official openHAB Alexa skill since currently, there is no way to have such customized settings at the skill level.

The only solution I can see is to run your own version of the skill and back-end function using the installation steps listed in the [README ](https://github.com/openhab/openhab-alexa/blob/master/README.md) file and point the host to your self hosted openhab-cloud server in [config.js](https://github.com/openhab/openhab-alexa/blob/master/config_sample.js).

However, this skill is currently using a deprecated version (v2) of the Alexa Skill API and you may have to wait for the v3 version to be published. You can refer to #54 for more information.

**Comment by devkid** [comment]
Didn't test it yet, but doesn't the [`README.me`](https://github.com/openhab/openhab-alexa/blob/master/README.md) describe exactly what you want? You only need to edit and rename `config_sample.js` and `env_sample` and can deploy your own Alexa skill (which you don't need to publish), backed by a Lambda function that has your configuration and relays your Alexa requests to your own OpenHAB installation.

**Comment by digitaldan** [comment]
Closing as this is already supported

>However, this skill is currently using a deprecated version (v2) of the Alexa Skill API and you may have to wait for the v3 version to be published. 

Yes and no, you can still select v2 through a workaround, they only disable selection in the actual html (weird), so if you enable the selection through something like the chrome inspector you can select v2 and submit it.  Surprised that it actually worked for me.
