### ISSUE TITLE
Support for new contact and motion sensor API

### ISSUE THREAD

**Issue by redeye86** [openhab/openhab-alexa#95]
It seems that amazon just activated support for contact and motion sensors that can be used in routines. The primary purpose is to let iot devices trigger rules but i think it should also be possible to let openhab send arbitrary status updates to alexa, which in turn can be used to trigger routines. 

Essentially this means that two-way communication would be possible without the echo-binding which uses an inofficial api and therefore has some authentication issues (at least when using 2FA).

**Comment by jsetton** [comment]
One thing to note with these sensors is that even though there are now supported, they can't be used as trigger device in routines since there are defined as `proactivelyReported=false` and the current v3 implementation doesn't support that feature. So basically, there isn't much use for them at the moment.
