### ISSUE TITLE
Alexa OpenHAB skill in Italy

### ISSUE THREAD

**Issue by giusanny** [openhab/openhab-alexa#97]
Hi all,
when do you think will the OpenHAB skill be In Italy?

**Comment by simoneluconi** [comment]
I think it's preatty much ready, here there are the publishing information: https://github.com/openhab/openhab-alexa/blob/master/res/PublishingInformation_it_IT.txt

**Comment by andrea-daru** [comment]
News about the publication date?

**Comment by Chanete** [comment]
Hi, same happens in Spain, last tuesday Alexa was lauched in Spanish and the openhab Skill is not availvable at Alexa.es 

Could you please publish it?

Thx!!!

**Comment by chrjs** [comment]
I published a private "BETA" for Italy. I can give access to someone interested. Just send me your alexa email account.

**Comment by andrea-daru** [comment]
Is there a way to send you email in private? 🤣

**Comment by chrjs** [comment]
@andrea-daru you could enter here, register and open a new ticket:
https://quickbookmarks.zendesk.com/access/unauthenticated?theme=hc
I'll receive the ticket.

**Comment by andrea-daru** [comment]
@chrjs it doesn't work 😢 Anyway I can connect the email used in github to alexa andrea.daru@gmail.com

**Comment by chrjs** [comment]
Now should work, sorry is was temporarily disabled. Ok :)

**Comment by chrjs** [comment]
Unfortunately seems I can't share my private beta. I'm not 100% sure but I think I cannot configure Alexa to authenticate with OAuth2 to OpenHab Cloud because I need some ClientId+Secret to authorize the call. Can someone confirm that OpenHab Cloud does not allow any OAuth2 client but only "certified" ones?

In case it is not possible, we definitely need to wait for an official release or each one of you should create his own beta skill on Alexa portal and configure it with their account via the "userpass" field in the config.js file.

**Comment by simeonruiz** [comment]
Is there any guidance to create our own beta?
 I would be very interested in this as just bought the echo device to be used for home automation.

Thx!!!

**Comment by giusanny** [comment]
Hi, any news on this? How can we help to get it?

**Comment by kaikreuzer** [comment]
It has been published today! 🎉
